// ============================================================
// MC Icon helper — uses mc-heads.net / sky.shiiyu.moe / crafatar
// For items we use the Hypixel Skyblock item texture IDs via mc.nerothe.com
// ============================================================
const MC_ICON = {
    // Farming
    enchantedWheat:       "https://mc.nerothe.com/img/1.20.4/wheat.png",
    enchantedCarrot:      "https://mc.nerothe.com/img/1.20.4/carrot.png",
    enchantedPotato:      "https://mc.nerothe.com/img/1.20.4/potato.png",
    enchantedSugarCane:   "https://mc.nerothe.com/img/1.20.4/sugar_cane.png",
    enchantedPumpkin:     "https://mc.nerothe.com/img/1.20.4/pumpkin_side.png",
    enchantedMelon:       "https://mc.nerothe.com/img/1.20.4/melon_side.png",
    enchantedCactus:      "https://mc.nerothe.com/img/1.20.4/cactus_side.png",
    enchantedCocoa:       "https://mc.nerothe.com/img/1.20.4/cocoa_beans.png",
    netherWart:           "https://mc.nerothe.com/img/1.20.4/nether_wart.png",
    // Mining
    enchantedDiamond:     "https://mc.nerothe.com/img/1.20.4/diamond.png",
    enchantedEmerald:     "https://mc.nerothe.com/img/1.20.4/emerald.png",
    enchantedGold:        "https://mc.nerothe.com/img/1.20.4/gold_ingot.png",
    enchantedIron:        "https://mc.nerothe.com/img/1.20.4/iron_ingot.png",
    enchantedLapis:       "https://mc.nerothe.com/img/1.20.4/lapis_lazuli.png",
    enchantedRedstone:    "https://mc.nerothe.com/img/1.20.4/redstone.png",
    enchantedCoal:        "https://mc.nerothe.com/img/1.20.4/coal.png",
    enchantedObsidian:    "https://mc.nerothe.com/img/1.20.4/obsidian.png",
    mithril:              "https://mc.nerothe.com/img/1.20.4/prismarine_shard.png",
    titanium:             "https://mc.nerothe.com/img/1.20.4/iron_nugget.png",
    gemstone:             "https://mc.nerothe.com/img/1.20.4/amethyst_shard.png",
    // Combat
    enchantedBone:        "https://mc.nerothe.com/img/1.20.4/bone.png",
    enchantedGunpowder:   "https://mc.nerothe.com/img/1.20.4/gunpowder.png",
    enchantedRottenFlesh: "https://mc.nerothe.com/img/1.20.4/rotten_flesh.png",
    enchantedEnderPearl:  "https://mc.nerothe.com/img/1.20.4/ender_pearl.png",
    enchantedBlazePowder: "https://mc.nerothe.com/img/1.20.4/blaze_powder.png",
    enchantedGhastTear:   "https://mc.nerothe.com/img/1.20.4/ghast_tear.png",
    enchantedSlimeBall:   "https://mc.nerothe.com/img/1.20.4/slime_ball.png",
    enchantedSpiderEye:   "https://mc.nerothe.com/img/1.20.4/spider_eye.png",
    // Wood & Fishing
    enchantedOakWood:     "https://mc.nerothe.com/img/1.20.4/oak_log.png",
    enchantedSpruceWood:  "https://mc.nerothe.com/img/1.20.4/spruce_log.png",
    enchantedBirchWood:   "https://mc.nerothe.com/img/1.20.4/birch_log.png",
    enchantedJungleWood:  "https://mc.nerothe.com/img/1.20.4/jungle_log.png",
    enchantedAcaciaWood:  "https://mc.nerothe.com/img/1.20.4/acacia_log.png",
    enchantedDarkOakWood: "https://mc.nerothe.com/img/1.20.4/dark_oak_log.png",
    enchantedClownfish:   "https://mc.nerothe.com/img/1.20.4/tropical_fish.png",
    enchantedPufferfish:  "https://mc.nerothe.com/img/1.20.4/pufferfish.png",
    enchantedRawSalmon:   "https://mc.nerothe.com/img/1.20.4/raw_salmon.png",
    // Enchanting
    grandExpBottle:       "https://mc.nerothe.com/img/1.20.4/experience_bottle.png",
    enchantedBook:        "https://mc.nerothe.com/img/1.20.4/enchanted_book.png",
    // Misc
    boosterCookie:        "https://mc.nerothe.com/img/1.20.4/cookie.png",
    bits:                 "https://mc.nerothe.com/img/1.20.4/nether_star.png",
    hyperCatalyst:        "https://mc.nerothe.com/img/1.20.4/end_crystal.png",
    // Gear icons
    sword:                "https://mc.nerothe.com/img/1.20.4/diamond_sword.png",
    bow:                  "https://mc.nerothe.com/img/1.20.4/bow.png",
    armor:                "https://mc.nerothe.com/img/1.20.4/diamond_chestplate.png",
    pickaxe:              "https://mc.nerothe.com/img/1.20.4/diamond_pickaxe.png",
    axe:                  "https://mc.nerothe.com/img/1.20.4/diamond_axe.png",
    rod:                  "https://mc.nerothe.com/img/1.20.4/fishing_rod.png",
    hoe:                  "https://mc.nerothe.com/img/1.20.4/diamond_hoe.png",
    potion:               "https://mc.nerothe.com/img/1.20.4/potion.png",
    goldenApple:          "https://mc.nerothe.com/img/1.20.4/golden_apple.png",
    // Mob icons
    zombie:               "https://mc-heads.net/head/zombie/32",
    skeleton:             "https://mc-heads.net/head/skeleton/32",
    enderman:             "https://mc-heads.net/head/enderman/32",
    spider:               "https://mc-heads.net/head/spider/32",
    blaze:                "https://mc-heads.net/head/blaze/32",
    ghast:                "https://mc-heads.net/head/ghast/32",
    slime:                "https://mc-heads.net/head/slime/32",
    magmaCube:            "https://mc-heads.net/head/magma_cube/32",
    witherSkeleton:       "https://mc-heads.net/head/wither_skeleton/32",
    pigman:               "https://mc-heads.net/head/zombie_pigman/32",
    creeper:              "https://mc-heads.net/head/creeper/32",
    witch:                "https://mc-heads.net/head/witch/32",
    guardian:             "https://mc-heads.net/head/guardian/32",
    wither:               "https://mc-heads.net/head/wither/32",
    dragon:               "https://mc-heads.net/head/ender_dragon/32",
    // Fallback
    unknown:              "https://mc.nerothe.com/img/1.20.4/barrier.png",
};

// ============================================================
// BAZAAR DATA
// ============================================================
const BAZAAR_DATA = [
    // Farming
    { name: "Enchanted Wheat", icon: MC_ICON.enchantedWheat, category: "farming", buyPrice: 432, sellPrice: 396, volume: 2841200 },
    { name: "Enchanted Carrot", icon: MC_ICON.enchantedCarrot, category: "farming", buyPrice: 1280, sellPrice: 1190, volume: 1524000 },
    { name: "Enchanted Potato", icon: MC_ICON.enchantedPotato, category: "farming", buyPrice: 980, sellPrice: 910, volume: 1890000 },
    { name: "Enchanted Sugar Cane", icon: MC_ICON.enchantedSugarCane, category: "farming", buyPrice: 3450, sellPrice: 3200, volume: 1120000 },
    { name: "Enchanted Pumpkin", icon: MC_ICON.enchantedPumpkin, category: "farming", buyPrice: 1630, sellPrice: 1480, volume: 982000 },
    { name: "Enchanted Melon Block", icon: MC_ICON.enchantedMelon, category: "farming", buyPrice: 2100, sellPrice: 1950, volume: 845000 },
    { name: "Enchanted Cactus Green", icon: MC_ICON.enchantedCactus, category: "farming", buyPrice: 780, sellPrice: 720, volume: 634000 },
    { name: "Enchanted Cocoa Beans", icon: MC_ICON.enchantedCocoa, category: "farming", buyPrice: 2800, sellPrice: 2620, volume: 720000 },
    { name: "Mutant Nether Wart", icon: MC_ICON.netherWart, category: "farming", buyPrice: 18500, sellPrice: 17200, volume: 412000 },
    // Mining
    { name: "Enchanted Diamond Block", icon: MC_ICON.enchantedDiamond, category: "mining", buyPrice: 204800, sellPrice: 198000, volume: 148000 },
    { name: "Enchanted Emerald Block", icon: MC_ICON.enchantedEmerald, category: "mining", buyPrice: 179200, sellPrice: 172500, volume: 132000 },
    { name: "Enchanted Gold Block", icon: MC_ICON.enchantedGold, category: "mining", buyPrice: 102400, sellPrice: 96800, volume: 256000 },
    { name: "Enchanted Iron Block", icon: MC_ICON.enchantedIron, category: "mining", buyPrice: 51200, sellPrice: 48400, volume: 312000 },
    { name: "Enchanted Lapis Block", icon: MC_ICON.enchantedLapis, category: "mining", buyPrice: 44800, sellPrice: 42100, volume: 289000 },
    { name: "Enchanted Redstone Block", icon: MC_ICON.enchantedRedstone, category: "mining", buyPrice: 38400, sellPrice: 36200, volume: 340000 },
    { name: "Enchanted Coal Block", icon: MC_ICON.enchantedCoal, category: "mining", buyPrice: 25600, sellPrice: 24100, volume: 420000 },
    { name: "Enchanted Obsidian", icon: MC_ICON.enchantedObsidian, category: "mining", buyPrice: 7200, sellPrice: 6800, volume: 580000 },
    { name: "Refined Mithril", icon: MC_ICON.mithril, category: "mining", buyPrice: 38000, sellPrice: 35600, volume: 186000 },
    { name: "Refined Titanium", icon: MC_ICON.titanium, category: "mining", buyPrice: 98000, sellPrice: 92400, volume: 94000 },
    { name: "Perfect Jasper Gemstone", icon: MC_ICON.gemstone, category: "mining", buyPrice: 420000, sellPrice: 398000, volume: 42000 },
    // Combat
    { name: "Enchanted Bone Block", icon: MC_ICON.enchantedBone, category: "combat", buyPrice: 14200, sellPrice: 13100, volume: 524000 },
    { name: "Enchanted Gunpowder", icon: MC_ICON.enchantedGunpowder, category: "combat", buyPrice: 5600, sellPrice: 5100, volume: 682000 },
    { name: "Enchanted Rotten Flesh", icon: MC_ICON.enchantedRottenFlesh, category: "combat", buyPrice: 1400, sellPrice: 1280, volume: 1240000 },
    { name: "Enchanted Ender Pearl", icon: MC_ICON.enchantedEnderPearl, category: "combat", buyPrice: 7200, sellPrice: 6600, volume: 720000 },
    { name: "Enchanted Eye of Ender", icon: MC_ICON.enchantedEnderPearl, category: "combat", buyPrice: 52000, sellPrice: 48600, volume: 145000 },
    { name: "Enchanted Blaze Powder", icon: MC_ICON.enchantedBlazePowder, category: "combat", buyPrice: 18400, sellPrice: 17100, volume: 380000 },
    { name: "Enchanted Ghast Tear", icon: MC_ICON.enchantedGhastTear, category: "combat", buyPrice: 42000, sellPrice: 39200, volume: 89000 },
    { name: "Enchanted Slime Block", icon: MC_ICON.enchantedSlimeBall, category: "combat", buyPrice: 24000, sellPrice: 22400, volume: 196000 },
    // Wood
    { name: "Enchanted Oak Wood", icon: MC_ICON.enchantedOakWood, category: "wood", buyPrice: 3200, sellPrice: 2940, volume: 612000 },
    { name: "Enchanted Spruce Wood", icon: MC_ICON.enchantedSpruceWood, category: "wood", buyPrice: 3800, sellPrice: 3510, volume: 524000 },
    { name: "Enchanted Birch Wood", icon: MC_ICON.enchantedBirchWood, category: "wood", buyPrice: 3600, sellPrice: 3340, volume: 480000 },
    { name: "Enchanted Jungle Wood", icon: MC_ICON.enchantedJungleWood, category: "wood", buyPrice: 4800, sellPrice: 4420, volume: 320000 },
    { name: "Enchanted Acacia Wood", icon: MC_ICON.enchantedAcaciaWood, category: "wood", buyPrice: 4200, sellPrice: 3880, volume: 298000 },
    { name: "Enchanted Dark Oak Wood", icon: MC_ICON.enchantedDarkOakWood, category: "wood", buyPrice: 5400, sellPrice: 4960, volume: 410000 },
    // Enchanting
    { name: "Grand Exp Bottle", icon: MC_ICON.grandExpBottle, category: "enchanting", buyPrice: 28000, sellPrice: 26200, volume: 245000 },
    { name: "Titanic Exp Bottle", icon: MC_ICON.grandExpBottle, category: "enchanting", buyPrice: 185000, sellPrice: 174000, volume: 68000 },
    { name: "Booster Cookie", icon: MC_ICON.boosterCookie, category: "enchanting", buyPrice: 1920000, sellPrice: 1860000, volume: 32000 },
    { name: "Hyper Catalyst", icon: MC_ICON.hyperCatalyst, category: "enchanting", buyPrice: 3200000, sellPrice: 3050000, volume: 12000 },
];

// Calculate margin and profit % for each item
BAZAAR_DATA.forEach(item => {
    item.margin = item.buyPrice - item.sellPrice;
    item.profitPct = ((item.margin / item.sellPrice) * 100).toFixed(1);
});

// ============================================================
// TOP RESELL DATA
// ============================================================
const RESELL_DATA = {
    "bazaar-flip": [
        { name: "Booster Cookie", icon: MC_ICON.boosterCookie, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 1860000, sell: 1920000, profit: 60000, profitPct: "3.2%" },
        { name: "Hyper Catalyst", icon: MC_ICON.hyperCatalyst, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 3050000, sell: 3200000, profit: 150000, profitPct: "4.9%" },
        { name: "Titanic Exp Bottle", icon: MC_ICON.grandExpBottle, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 174000, sell: 185000, profit: 11000, profitPct: "6.3%" },
        { name: "Enchanted Diamond Block", icon: MC_ICON.enchantedDiamond, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 198000, sell: 204800, profit: 6800, profitPct: "3.4%" },
        { name: "Perfect Jasper Gemstone", icon: MC_ICON.gemstone, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 398000, sell: 420000, profit: 22000, profitPct: "5.5%" },
        { name: "Refined Titanium", icon: MC_ICON.titanium, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 92400, sell: 98000, profit: 5600, profitPct: "6.1%" },
        { name: "Enchanted Ghast Tear", icon: MC_ICON.enchantedGhastTear, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 39200, sell: 42000, profit: 2800, profitPct: "7.1%" },
        { name: "Enchanted Eye of Ender", icon: MC_ICON.enchantedEnderPearl, type: "Bazaar", buyFrom: "Buy Order", sellTo: "Sell Order", buy: 48600, sell: 52000, profit: 3400, profitPct: "7.0%" },
    ],
    "ah-flip": [
        { name: "Hyperion", icon: MC_ICON.sword, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 680000000, sell: 720000000, profit: 40000000, profitPct: "5.9%" },
        { name: "Terminator", icon: MC_ICON.bow, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 520000000, sell: 560000000, profit: 40000000, profitPct: "7.7%" },
        { name: "Storm Armor Set", icon: MC_ICON.armor, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 120000000, sell: 140000000, profit: 20000000, profitPct: "16.7%" },
        { name: "Necron Armor Set", icon: MC_ICON.armor, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 180000000, sell: 210000000, profit: 30000000, profitPct: "16.7%" },
        { name: "Warden Helmet", icon: MC_ICON.armor, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 280000000, sell: 320000000, profit: 40000000, profitPct: "14.3%" },
        { name: "Giant's Sword", icon: MC_ICON.sword, type: "Auction", buyFrom: "BIN Snipe", sellTo: "BIN Relist", buy: 340000000, sell: 380000000, profit: 40000000, profitPct: "11.8%" },
    ],
    "npc-sell": [
        { name: "Enchanted Coal Block", icon: MC_ICON.enchantedCoal, type: "NPC", buyFrom: "Bazaar BO", sellTo: "NPC", buy: 24100, sell: 25600, profit: 1500, profitPct: "6.2%" },
        { name: "Enchanted Gold Block", icon: MC_ICON.enchantedGold, type: "NPC", buyFrom: "Bazaar BO", sellTo: "NPC", buy: 96800, sell: 102400, profit: 5600, profitPct: "5.8%" },
        { name: "Enchanted Iron Block", icon: MC_ICON.enchantedIron, type: "NPC", buyFrom: "Bazaar BO", sellTo: "NPC", buy: 48400, sell: 51200, profit: 2800, profitPct: "5.8%" },
        { name: "Enchanted Lapis Block", icon: MC_ICON.enchantedLapis, type: "NPC", buyFrom: "Bazaar BO", sellTo: "NPC", buy: 42100, sell: 44800, profit: 2700, profitPct: "6.4%" },
        { name: "Enchanted Redstone Block", icon: MC_ICON.enchantedRedstone, type: "NPC", buyFrom: "Bazaar BO", sellTo: "NPC", buy: 36200, sell: 38400, profit: 2200, profitPct: "6.1%" },
    ],
    "craft-flip": [
        { name: "Enchanted Bookshelf", icon: MC_ICON.enchantedBook, type: "Craft", buyFrom: "Craft from parts", sellTo: "Sell Order", buy: 16000, sell: 19200, profit: 3200, profitPct: "20.0%" },
        { name: "Enchanted Fermented Spider Eye", icon: MC_ICON.enchantedSpiderEye, type: "Craft", buyFrom: "Craft from parts", sellTo: "Sell Order", buy: 8400, sell: 11200, profit: 2800, profitPct: "33.3%" },
        { name: "Polished Pumpkin", icon: MC_ICON.enchantedPumpkin, type: "Craft", buyFrom: "Craft from parts", sellTo: "Sell Order", buy: 9800, sell: 13500, profit: 3700, profitPct: "37.8%" },
        { name: "Enchanted Cookie", icon: MC_ICON.boosterCookie, type: "Craft", buyFrom: "Craft from parts", sellTo: "Sell Order", buy: 5200, sell: 7100, profit: 1900, profitPct: "36.5%" },
    ],
};

// ============================================================
// MONEY METHODS DATA
// ============================================================
const MONEY_METHODS = [
    // Early Game
    {
        id: "zealot-grinding",
        name: "Zealot Grinding",
        subtitle: "Classic early-game money method",
        icon: MC_ICON.enchantedEnderPearl,
        difficulty: "early",
        earningRate: "500K-1M/hr",
        tags: [
            { text: "Early Game", color: "var(--green)", bg: "var(--green-dim)" },
            { text: "Combat", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Kill Zealots in the Dragon's Nest until a Special Zealot spawns that drops a Summoning Eye worth ~500K coins.",
            steps: [
                "Get at least Ender Armor and an AOTE (Aspect of the End)",
                "Head to the Dragon's Nest in The End",
                "Kill Zealots — every ~420 kills, a Special Zealot spawns",
                "Special Zealots drop Summoning Eyes (~500K each)",
                "Use a weapon with Telekinesis to auto-pickup drops",
                "Sell Summoning Eyes on the Bazaar or save 8 for a dragon fight",
            ],
            gear: [
                { name: "Ender Armor", icon: MC_ICON.armor },
                { name: "Aspect of the End", icon: MC_ICON.sword },
                { name: "God Potion", icon: MC_ICON.potion },
            ],
        },
    },
    {
        id: "pumpkin-farming",
        name: "Pumpkin Farming",
        subtitle: "AFK-friendly early money",
        icon: MC_ICON.enchantedPumpkin,
        difficulty: "early",
        earningRate: "800K-1.5M/hr",
        tags: [
            { text: "Early Game", color: "var(--green)", bg: "var(--green-dim)" },
            { text: "Farming", color: "var(--accent)", bg: "var(--accent-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Build a large pumpkin farm on your island and use a farming tool to harvest. Sell Enchanted Pumpkins on the Bazaar.",
            steps: [
                "Unlock Farming on your island (Farming skill level 1+)",
                "Build rows of pumpkins with water channels in between",
                "Craft a Pumpkin Dicer or Fermento/Turbo-Crop hoe",
                "Farm pumpkins and craft Enchanted Pumpkins (160 pumpkins each)",
                "Sell on Bazaar or NPC depending on current prices",
                "Use Farming Fortune gear for maximum yield",
            ],
            gear: [
                { name: "Rancher's Boots", icon: MC_ICON.armor },
                { name: "Pumpkin Dicer", icon: MC_ICON.hoe },
                { name: "Farm Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        id: "potato-farming",
        name: "Potato / Carrot Farming",
        subtitle: "Solid consistent early income",
        icon: MC_ICON.enchantedPotato,
        difficulty: "early",
        earningRate: "600K-1.2M/hr",
        tags: [
            { text: "Early Game", color: "var(--green)", bg: "var(--green-dim)" },
            { text: "Farming", color: "var(--accent)", bg: "var(--accent-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Build potato or carrot farms and sell enchanted versions on the Bazaar. Good starter income.",
            steps: [
                "Build layered potato or carrot farms on your island",
                "Use a farming hoe (Turbo-Crop Hoe recommended)",
                "Enable auto-replant with Replenish enchantment",
                "Sell Enchanted Potatoes/Carrots on Bazaar",
                "Upgrade to Legendary Elephant pet for extra farming fortune",
            ],
            gear: [
                { name: "Turbo-Crop Hoe", icon: MC_ICON.hoe },
                { name: "Farm Armor", icon: MC_ICON.armor },
                { name: "Rancher's Boots", icon: MC_ICON.armor },
            ],
        },
    },
    {
        id: "foraging",
        name: "Dark Oak Foraging",
        subtitle: "Early money with treecapitator",
        icon: MC_ICON.enchantedDarkOakWood,
        difficulty: "early",
        earningRate: "400K-800K/hr",
        tags: [
            { text: "Early Game", color: "var(--green)", bg: "var(--green-dim)" },
            { text: "Foraging", color: "var(--blue)", bg: "var(--blue-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Chop dark oak trees in the Park with a Treecapitator for fast wood collection and sell enchanted logs.",
            steps: [
                "Obtain a Treecapitator (costs ~3M, huge upgrade)",
                "Go to the Dark Thicket in the Park",
                "Chop dark oak trees — Treecapitator breaks entire trees",
                "Craft into Enchanted Dark Oak and sell on Bazaar",
                "Use Monkey pet for extra foraging speed",
            ],
            gear: [
                { name: "Treecapitator", icon: MC_ICON.axe },
                { name: "Monkey Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    // Mid Game
    {
        id: "sugar-cane-farming",
        name: "Sugar Cane Farming",
        subtitle: "Top mid-game farming method",
        icon: MC_ICON.enchantedSugarCane,
        difficulty: "mid",
        earningRate: "3M-6M/hr",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Farming", color: "var(--accent)", bg: "var(--accent-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Build a massive sugar cane farm and use a high-tier hoe with Farming Fortune armor. One of the best consistent methods.",
            steps: [
                "Build multi-layered sugar cane farms (at least 4 layers)",
                "Get a Cactus Knife or Sugar Cane Hoe (T3 recommended)",
                "Use full Fermento Armor for extra Farming Fortune",
                "Use Elephant pet (Legendary) for the farming fortune boost",
                "Sell Enchanted Sugar Cane on Bazaar",
                "With max setup, you can hit 6M+/hr easily",
            ],
            gear: [
                { name: "Sugar Cane Hoe T3", icon: MC_ICON.hoe },
                { name: "Fermento Armor", icon: MC_ICON.armor },
                { name: "Elephant Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "bazaar-flipping",
        name: "Bazaar Flipping",
        subtitle: "Buy low, sell high on the Bazaar",
        icon: MC_ICON.enchantedEmerald,
        difficulty: "mid",
        earningRate: "2M-10M/hr",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Flipping", color: "var(--purple)", bg: "var(--purple-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Place buy orders for items at low prices, then immediately sell them with sell orders at a higher price. The margin is your profit.",
            steps: [
                "Check the Bazaar Tracker (this site!) for items with high margins",
                "Place buy orders at the current buy price",
                "Wait for orders to fill (can take minutes to hours)",
                "Place sell orders at the current sell price",
                "Repeat with multiple items to maximize throughput",
                "Focus on high-volume items so orders fill quickly",
                "Start with cheaper items and scale up as you learn patterns",
            ],
            gear: [
                { name: "Coins to invest", icon: MC_ICON.enchantedGold },
                { name: "Booster Cookie", icon: MC_ICON.boosterCookie },
            ],
        },
    },
    {
        id: "slayer-revenant",
        name: "Revenant Slayer (T5)",
        subtitle: "Combat money method with rare RNG drops",
        icon: MC_ICON.enchantedRottenFlesh,
        difficulty: "mid",
        earningRate: "2M-5M/hr (RNG dependent)",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Combat", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Grind Revenant Horror T5 slayer bosses for rare drops like the Scythe Blade and Warden Heart.",
            steps: [
                "Reach Zombie Slayer level 5+ to unlock T5 bosses",
                "Get strong combat gear (Shadow Fury + 3/4 SA recommended)",
                "Start T5 Revenant quests from Maddox",
                "Kill zombies in the Crypts to spawn the boss",
                "Defeat the boss and collect loot",
                "Pray for Warden Heart drop (~1/25000) worth 400M+",
                "Regular drops (Revenant Flesh etc) provide consistent income",
            ],
            gear: [
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
                { name: "Shadow Fury", icon: MC_ICON.sword },
                { name: "Mana Flux Orb", icon: MC_ICON.bits },
            ],
        },
    },
    {
        id: "mining-gemstones",
        name: "Gemstone Mining",
        subtitle: "Mine gemstones in the Crystal Hollows",
        icon: MC_ICON.gemstone,
        difficulty: "mid",
        earningRate: "4M-8M/hr",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Mining", color: "var(--cyan)", bg: "rgba(6,182,212,0.12)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Mine gemstones in the Crystal Hollows with a Gemstone Gauntlet or high-tier drill. Very profitable with the right setup.",
            steps: [
                "Get Heart of the Mountain (HOTM) to at least level 6",
                "Unlock the Crystal Hollows from the Dwarven Mines",
                "Get a Gemstone Gauntlet (or higher tier drill)",
                "Focus on Jade or Jasper gemstones for max profit",
                "Use a Blue Cheese Goblin Omelette for fortune",
                "Use Bal pet for extra mining speed in magma fields",
                "Sell perfect gems on the Bazaar",
            ],
            gear: [
                { name: "Gemstone Gauntlet", icon: MC_ICON.pickaxe },
                { name: "Sorrow Armor", icon: MC_ICON.armor },
                { name: "Bal Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    // Late Game
    {
        id: "dungeons-f7",
        name: "Floor 7 Dungeon Runs",
        subtitle: "Consistent high-level income",
        icon: MC_ICON.sword,
        difficulty: "late",
        earningRate: "8M-20M/hr",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Dungeons", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Run Floor 7 (Goldor) dungeons for Necron armor drops, Wither Essence, and rare items. Very profitable with fast clear times.",
            steps: [
                "Reach Catacombs level 30+ for efficient F7 runs",
                "Get a solid dungeon party (Archer/Bers/Mage/Tank/Healer)",
                "Use S+ completion for maximum drops",
                "Sell Wither Essence and dungeon drops on AH",
                "Target 5-7 minute clear times for best profit/hr",
                "Look for rare Handle drops (~200M+)",
                "Sell Necron pieces individually for profit",
            ],
            gear: [
                { name: "Necron's Armor", icon: MC_ICON.armor },
                { name: "Hyperion/Terminator", icon: MC_ICON.sword },
                { name: "Golden Dragon Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "nether-wart-farming",
        name: "Nether Wart Farming (Maxed)",
        subtitle: "Best farming method with max setup",
        icon: MC_ICON.netherWart,
        difficulty: "late",
        earningRate: "10M-18M/hr",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Farming", color: "var(--accent)", bg: "var(--accent-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "With a fully maxed Nether Wart setup, this is the most profitable farming method in the game.",
            steps: [
                "Build a massive nether wart farm (5+ layers)",
                "Get a T3 Nether Wart Hoe (fully maxed with recombobulator)",
                "Use Fermento Armor with full enchants",
                "Use Elephant Pet (Legendary, level 100)",
                "Enable all farming fortune upgrades (Anita shop, etc.)",
                "Sell Mutant Nether Wart on Bazaar",
                "With 1800+ farming fortune you'll earn 15M+/hr",
            ],
            gear: [
                { name: "Nether Wart Hoe T3", icon: MC_ICON.hoe },
                { name: "Fermento Armor", icon: MC_ICON.armor },
                { name: "Elephant Pet (Leg)", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "ah-flipping",
        name: "Auction House Flipping",
        subtitle: "High-risk high-reward flipping",
        icon: MC_ICON.enchantedDiamond,
        difficulty: "late",
        earningRate: "10M-50M+/hr",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Flipping", color: "var(--purple)", bg: "var(--purple-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Buy underpriced items from the AH (BIN snipes) and relist at market value. Requires game knowledge and fast reflexes.",
            steps: [
                "Learn the market prices of popular items by heart",
                "Search AH for specific items and sort by BIN lowest",
                "Look for items listed below their actual value",
                "Buy them instantly and relist at the correct price",
                "Focus on items you know well (armors, weapons, pets)",
                "Use /ah and filter by specific categories",
                "Start with 10-50M budget, scale up as you learn",
                "Beware of manipulation and fake price pumps",
            ],
            gear: [
                { name: "Large Coin Balance", icon: MC_ICON.enchantedGold },
                { name: "Booster Cookie", icon: MC_ICON.boosterCookie },
            ],
        },
    },
    {
        id: "voidgloom-slayer",
        name: "Voidgloom Seraph (T4)",
        subtitle: "End-game enderman slayer grind",
        icon: MC_ICON.enchantedEnderPearl,
        difficulty: "late",
        earningRate: "5M-15M/hr (RNG dependent)",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Combat", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Grind Voidgloom T4 slayers for rare drops like Judgement Core and Etherwarp Conduit. Very profitable if you hit RNG.",
            steps: [
                "Reach Enderman Slayer 7 to unlock T4",
                "Get Terminator bow or Juju Shortbow with full SE5",
                "Use Warden Helmet + Necron armor for survivability",
                "Kill endermen in The End to spawn the boss",
                "Use Voidgloom-specific strategies (void hits, hitshield breaking)",
                "Sell rare drops (Judgement Core = 200M+, Etherwarp Conduit = 50M+)",
                "Normal drops provide 2-3M/hr base income",
            ],
            gear: [
                { name: "Terminator Bow", icon: MC_ICON.bow },
                { name: "Warden Helmet", icon: MC_ICON.armor },
                { name: "Necron's Armor", icon: MC_ICON.armor },
            ],
        },
    },
    // End Game
    {
        id: "m7-dungeons",
        name: "Master Mode Floor 7",
        subtitle: "Highest dungeon income",
        icon: MC_ICON.sword,
        difficulty: "end",
        earningRate: "30M-80M+/hr",
        tags: [
            { text: "End Game", color: "var(--orange)", bg: "rgba(249,115,22,0.12)" },
            { text: "Dungeons", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Master Mode F7 is the ultimate dungeon grind. Handle drops alone can make you billions. Requires max gear and high skill.",
            steps: [
                "Reach Catacombs level 45+ (50 preferred)",
                "Get maxed Hyperion and full Goldor/Storm/Necron",
                "Find a consistent M7 party or guild",
                "Learn the Maxor/Storm/Goldor/Necron boss phases",
                "S+ runs give the best loot table",
                "Handle drop = 500M-800M+ profit",
                "Wither Essence alone = 5M+ per run",
                "Target sub 8 minute runs for best efficiency",
            ],
            gear: [
                { name: "Hyperion (Maxed)", icon: MC_ICON.sword },
                { name: "Goldor Armor", icon: MC_ICON.armor },
                { name: "Golden Dragon Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "kuudra-infernal",
        name: "Kuudra (Infernal T5)",
        subtitle: "Crimson Isle endgame boss",
        icon: MC_ICON.enchantedBlazePowder,
        difficulty: "end",
        earningRate: "25M-60M+/hr",
        tags: [
            { text: "End Game", color: "var(--orange)", bg: "rgba(249,115,22,0.12)" },
            { text: "Combat", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Infernal Kuudra (T5) drops extremely valuable Crimson Essence and rare armor attributes. Top tier money for geared players.",
            steps: [
                "Complete all Crimson Isle faction quests",
                "Get maxed Crimson/Terror/Aurora armor with good attributes",
                "Learn each Kuudra phase (supply, build, DPS, stun)",
                "Form a 4-player party with defined roles",
                "Sell Crimson Essence and attribute shards on AH",
                "Rare attribute combinations can sell for 100M+",
                "Godrolled armor pieces are worth billions",
                "Target sub 4 minute runs for maximum efficiency",
            ],
            gear: [
                { name: "Terror Armor (Maxed)", icon: MC_ICON.armor },
                { name: "Terminator Bow", icon: MC_ICON.bow },
                { name: "Golden Dragon Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "manipulating-market",
        name: "Bit Shopping",
        subtitle: "Use cookie bits for profit",
        icon: MC_ICON.bits,
        difficulty: "mid",
        earningRate: "1M-3M per cookie",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Passive", color: "var(--cyan)", bg: "rgba(6,182,212,0.12)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Buy Booster Cookies with coins, earn bits passively, and buy high-value items from the Bits Shop to resell.",
            steps: [
                "Buy a Booster Cookie from the Bazaar (~1.9M coins)",
                "Cookies give you bits passively over 4 days",
                "Each cookie gives approximately 4800 bits",
                "Buy God Potions from Elizabeth (1500 bits, sells for ~1.5M)",
                "Buy Kat Flowers (500 bits, sells for ~300K)",
                "Buy Enchanted Books from the bits shop for resale",
                "Net profit is roughly 1-3M per cookie depending on bit prices",
            ],
            gear: [
                { name: "Booster Cookie", icon: MC_ICON.boosterCookie },
                { name: "Coins", icon: MC_ICON.enchantedGold },
            ],
        },
    },
    {
        id: "fishing-lava",
        name: "Lava Fishing (Crimson Isle)",
        subtitle: "Fish for rare catches in lava",
        icon: MC_ICON.rod,
        difficulty: "late",
        earningRate: "5M-12M/hr",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Fishing", color: "var(--blue)", bg: "var(--blue-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Fish in lava on the Crimson Isle for rare sea creatures and valuable drops. Requires high fishing skill and specialized gear.",
            steps: [
                "Get Fishing level 30+ and unlock Crimson Isle fishing",
                "Get a Hellfire Rod or Inferno Rod",
                "Use Magma Lord Armor for lava fishing bonuses",
                "Fish in the Crimson Isle lava pools",
                "Kill lava sea creatures for rare drops",
                "Thunder and Lord Jawbus drops are worth millions",
                "Use Ammonite pet for extra sea creature chance",
            ],
            gear: [
                { name: "Inferno Rod", icon: MC_ICON.rod },
                { name: "Magma Lord Armor", icon: MC_ICON.armor },
                { name: "Ammonite Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "ghost-grinding",
        name: "Ghost Grinding",
        subtitle: "High-combat income in Dwarven Mines",
        icon: MC_ICON.enchantedGhastTear,
        difficulty: "mid",
        earningRate: "3M-7M/hr",
        tags: [
            { text: "Mid Game", color: "var(--blue)", bg: "var(--blue-dim)" },
            { text: "Combat", color: "var(--red)", bg: "var(--red-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "Kill Ghosts in the Dwarven Mines for Sorrow armor pieces and Volta drops. Good consistent combat money.",
            steps: [
                "Unlock the Mist area in the Dwarven Mines",
                "Get at least 3/4 SA armor or better",
                "Use a weapon with high damage and life steal",
                "Kill ghosts for Sorrow armor pieces (~5M each)",
                "Collect Ghostly Boots, Volta drops",
                "Use a combat pet like Tiger or Wither Skeleton",
                "Sell all drops on AH for maximum profit",
            ],
            gear: [
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
                { name: "Giant's Sword", icon: MC_ICON.sword },
                { name: "Wither Skeleton Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        id: "diana-event",
        name: "Mythological Event (Diana)",
        subtitle: "Seasonal event with huge payouts",
        icon: MC_ICON.goldenApple,
        difficulty: "late",
        earningRate: "15M-40M+/hr",
        tags: [
            { text: "Late Game", color: "var(--purple)", bg: "var(--purple-dim)" },
            { text: "Event", color: "var(--accent)", bg: "var(--accent-dim)" },
        ],
        videoId: "dQw4w9WgXcQ",
        guide: {
            summary: "During the Mayor Diana event, use Griffin Pet and Ancestral Spade to dig up mythological creatures and treasures.",
            steps: [
                "Wait for Diana to become Mayor (mythological ritual perk)",
                "Get a Legendary Griffin Pet (EPIC at minimum)",
                "Obtain an Ancestral Spade from the event",
                "Use the spade to dig up burrows around the Hub",
                "Kill mythological creatures for rare drops",
                "Chimera books, Minos Relics, and Daedalus Sticks are worth hundreds of millions",
                "Follow burrow chains for increasing rarity",
                "This is one of the most profitable events in the game",
            ],
            gear: [
                { name: "Griffin Pet (Leg)", icon: MC_ICON.goldenApple },
                { name: "Ancestral Spade", icon: MC_ICON.hoe },
                { name: "Strong Armor", icon: MC_ICON.armor },
            ],
        },
    },
];

// ============================================================
// MOB GUIDE DATA
// ============================================================
const MOB_GUIDE = [
    // Hub
    {
        name: "Zombie",
        icon: MC_ICON.zombie,
        location: "hub",
        locationName: "Graveyard (Hub)",
        health: "100",
        damage: "20",
        xp: "10",
        difficulty: 10,
        difficultyColor: "var(--green)",
        guide: {
            summary: "Basic mobs in the Graveyard. Great for beginners to level up Combat skill.",
            tips: [
                "Very easy — any starter weapon works",
                "Farm them in the Graveyard near the Crypts entrance",
                "Drop Rotten Flesh which can be sold or enchanted",
                "Use a weapon with Knockback or First Strike for faster kills",
                "Good for leveling up Combat skill early on",
            ],
            recommendedGear: [
                { name: "Undead Sword", icon: MC_ICON.sword },
                { name: "Zombie Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Skeleton",
        icon: MC_ICON.skeleton,
        location: "hub",
        locationName: "Graveyard (Hub)",
        health: "200",
        damage: "40",
        xp: "15",
        difficulty: 15,
        difficultyColor: "var(--green)",
        guide: {
            summary: "Ranged enemies in the Graveyard. Watch out for their arrows.",
            tips: [
                "They shoot arrows — strafe side to side to dodge",
                "Rush them quickly to minimize ranged damage",
                "Drop Bones and Arrows",
                "Slightly harder than Zombies but still beginner-friendly",
                "Use a shield or high-speed approach to close the gap",
            ],
            recommendedGear: [
                { name: "Undead Sword", icon: MC_ICON.sword },
                { name: "Lapis Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Creeper",
        icon: MC_ICON.creeper,
        location: "hub",
        locationName: "Wilderness (Hub)",
        health: "120",
        damage: "100 (explosion)",
        xp: "20",
        difficulty: 25,
        difficultyColor: "var(--green)",
        guide: {
            summary: "Explosive mobs — kill them before they detonate!",
            tips: [
                "They explode when close — kill them at range or very quickly",
                "No block damage in SkyBlock but they still hurt you",
                "Drop Gunpowder which crafts into Enchanted Gunpowder",
                "Use a bow or high-damage melee weapon",
                "Sprint-hit technique keeps you at safe distance",
            ],
            recommendedGear: [
                { name: "Runaan's Bow", icon: MC_ICON.bow },
                { name: "Growth Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Spider",
        icon: MC_ICON.spider,
        location: "hub",
        locationName: "Spider's Den",
        health: "180",
        damage: "35",
        xp: "15",
        difficulty: 20,
        difficultyColor: "var(--green)",
        guide: {
            summary: "Common enemies in the Spider's Den. Farm them for String and Spider Eyes.",
            tips: [
                "Found throughout the Spider's Den",
                "Drop String and Spider Eye",
                "Use Bane of Arthropods enchantment for extra damage",
                "Brood Mother boss spawns periodically — drops rare loot",
                "Great for leveling Combat 1-15",
            ],
            recommendedGear: [
                { name: "Spider Armor", icon: MC_ICON.armor },
                { name: "Silver Fang", icon: MC_ICON.sword },
            ],
        },
    },
    // Deep Caverns
    {
        name: "Lapis Zombie",
        icon: MC_ICON.zombie,
        location: "deep-caverns",
        locationName: "Lapis Quarry",
        health: "200",
        damage: "50",
        xp: "20",
        difficulty: 20,
        difficultyColor: "var(--green)",
        guide: {
            summary: "Zombies in the Lapis Quarry. Drop Lapis Armor pieces — essential early game.",
            tips: [
                "Found in the Lapis Quarry section of Deep Caverns",
                "Drop Lapis Armor pieces (excellent early armor set)",
                "Lapis Armor gives +200% XP bonus when full set worn",
                "Farm them until you have a full set",
                "Low difficulty — any decent weapon works",
            ],
            recommendedGear: [
                { name: "Undead Sword", icon: MC_ICON.sword },
                { name: "Any early armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Redstone Pigman",
        icon: MC_ICON.pigman,
        location: "deep-caverns",
        locationName: "Pigman's Den",
        health: "1500",
        damage: "120",
        xp: "50",
        difficulty: 35,
        difficultyColor: "var(--accent)",
        guide: {
            summary: "Tougher mobs in the Pigman's Den. Drop Pork and Redstone.",
            tips: [
                "Much higher health than previous mobs",
                "Deal significant damage — bring decent armor",
                "Drop Raw Porkchop and Redstone",
                "Good for leveling Combat to 15-20",
                "Recommended to have at least Hardened Diamond Armor",
            ],
            recommendedGear: [
                { name: "Hardened Diamond Armor", icon: MC_ICON.armor },
                { name: "Aspect of the End", icon: MC_ICON.sword },
            ],
        },
    },
    // The End
    {
        name: "Enderman",
        icon: MC_ICON.enderman,
        location: "end",
        locationName: "The End",
        health: "9000",
        damage: "500",
        xp: "150",
        difficulty: 45,
        difficultyColor: "var(--accent)",
        guide: {
            summary: "The primary mob in The End. Crucial for Enderman Slayer and Summoning Eye farming.",
            tips: [
                "Teleport away when hit — use weapons that prevent this",
                "Drop Ender Pearls, used for crafting Ender Armor",
                "Zealot variant spawns at Dragon's Nest (drops Summoning Eyes)",
                "Use AOTE ability to track and hit them quickly",
                "Full Ender Armor gives massive damage buff in The End (+100%)",
                "Always look at them to aggro them first",
            ],
            recommendedGear: [
                { name: "Ender Armor Set", icon: MC_ICON.armor },
                { name: "Aspect of the End", icon: MC_ICON.sword },
            ],
        },
    },
    {
        name: "Ender Dragon",
        icon: MC_ICON.dragon,
        location: "end",
        locationName: "Dragon's Nest",
        health: "7,500,000",
        damage: "2000",
        xp: "5000",
        difficulty: 85,
        difficultyColor: "var(--red)",
        guide: {
            summary: "The iconic boss of The End. Requires 8 Summoning Eyes to summon. Drops extremely rare and valuable items.",
            tips: [
                "Place 8 Summoning Eyes on the altars to summon",
                "Multiple dragon types: Protector, Old, Young, Strong, Wise, Superior, Unstable",
                "Superior Dragon is the rarest and most valuable",
                "Use a strong bow (Runaan's or better) for flying phase",
                "DPS the dragon when it perches on the center fountain",
                "Top 3 damage dealers get the best loot",
                "Dragon armor sets are some of the best in the game",
                "Bring lots of healing (Golden Apples, potions)",
            ],
            recommendedGear: [
                { name: "Strong Dragon Armor", icon: MC_ICON.armor },
                { name: "Runaan's Bow", icon: MC_ICON.bow },
                { name: "God Potion", icon: MC_ICON.potion },
            ],
        },
    },
    // Crimson Isle
    {
        name: "Blaze",
        icon: MC_ICON.blaze,
        location: "crimson",
        locationName: "Crimson Isle",
        health: "50,000",
        damage: "800",
        xp: "200",
        difficulty: 55,
        difficultyColor: "var(--orange)",
        guide: {
            summary: "Flying fire mobs on the Crimson Isle. Common target for Blaze Slayer.",
            tips: [
                "Fly and shoot fireballs — hard to reach without ranged",
                "Drop Blaze Rods for crafting Blaze Powder",
                "Use a bow or AOTE to reach them",
                "Blaze Slayer starts with these mobs",
                "Bring fire resistance potions for safety",
                "Higher level variants deal massive damage",
            ],
            recommendedGear: [
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
                { name: "Juju Shortbow", icon: MC_ICON.bow },
                { name: "Fire Res Potion", icon: MC_ICON.potion },
            ],
        },
    },
    {
        name: "Magma Cube (Boss)",
        icon: MC_ICON.magmaCube,
        location: "crimson",
        locationName: "Crimson Isle",
        health: "500,000",
        damage: "2000",
        xp: "800",
        difficulty: 70,
        difficultyColor: "var(--red)",
        guide: {
            summary: "Large magma cube bosses on the Crimson Isle. Part of the Kuudra questline.",
            tips: [
                "Splits into smaller cubes when killed — clear them all",
                "Very high health pool — need sustained DPS",
                "Drop Magma Cream and rare items",
                "Part of the Crimson Isle faction quests",
                "Use lifesteal and high-damage weapons",
                "Dodge their jump attacks — they deal massive damage on landing",
            ],
            recommendedGear: [
                { name: "Necron's Armor", icon: MC_ICON.armor },
                { name: "Giant's Sword", icon: MC_ICON.sword },
                { name: "Wither Skeleton Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        name: "Ghast",
        icon: MC_ICON.ghast,
        location: "crimson",
        locationName: "Crimson Isle",
        health: "80,000",
        damage: "1200",
        xp: "300",
        difficulty: 50,
        difficultyColor: "var(--accent)",
        guide: {
            summary: "Floating fire-breathing mobs. High in the sky — need ranged attacks.",
            tips: [
                "Float very high — MUST use a bow or ranged ability",
                "Their fireballs can be reflected back by hitting them",
                "Drop Ghast Tears — valuable for crafting and selling",
                "Use Terminator or Juju Shortbow for easy kills",
                "They have moderate health but are hard to reach",
                "Good consistent income if you can kill them quickly",
            ],
            recommendedGear: [
                { name: "Juju Shortbow", icon: MC_ICON.bow },
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
            ],
        },
    },
    // Slayers
    {
        name: "Revenant Horror (T5)",
        icon: MC_ICON.zombie,
        location: "slayer",
        locationName: "Slayer Boss",
        health: "1,500,000",
        damage: "3000",
        xp: "1500",
        difficulty: 75,
        difficultyColor: "var(--red)",
        guide: {
            summary: "Tier 5 Zombie Slayer boss. Drops rare items like Scythe Blade and Warden Heart.",
            tips: [
                "Spawns after killing enough zombies with the quest active",
                "Has multiple phases with increasing damage",
                "TNT phase: Run away when it spawns TNT around it",
                "Healing phase: It heals — burst it down quickly",
                "Use Reaper Falchion for bonus damage against undead",
                "Life steal is essential for survivability",
                "Warden Heart drop (1/25000) is worth 400M+",
                "Bring a Mana Flux Power Orb for sustain",
            ],
            recommendedGear: [
                { name: "Reaper Falchion", icon: MC_ICON.sword },
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
                { name: "Mana Flux Orb", icon: MC_ICON.bits },
            ],
        },
    },
    {
        name: "Sven Packmaster (T4)",
        icon: MC_ICON.slime,
        location: "slayer",
        locationName: "Slayer Boss",
        health: "2,000,000",
        damage: "4000",
        xp: "2000",
        difficulty: 70,
        difficultyColor: "var(--red)",
        guide: {
            summary: "Tier 4 Wolf Slayer boss. Drops Overflux Capacitor and Grizzly Bait.",
            tips: [
                "Spawns wolves that assist it — AoE attacks help",
                "Has a charge attack — dodge by moving sideways",
                "Wolf pups heal the boss — kill them first",
                "Use True Damage weapons if possible",
                "Overflux Capacitor drop is very valuable",
                "Bring Mana Flux orb for the fight",
                "Critical hits are key for fast kills",
            ],
            recommendedGear: [
                { name: "Shadow Fury", icon: MC_ICON.sword },
                { name: "Necron's Armor", icon: MC_ICON.armor },
                { name: "Tiger Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        name: "Voidgloom Seraph (T4)",
        icon: MC_ICON.enderman,
        location: "slayer",
        locationName: "Slayer Boss",
        health: "12,000,000",
        damage: "8000",
        xp: "5000",
        difficulty: 95,
        difficultyColor: "var(--red)",
        guide: {
            summary: "The hardest slayer boss. Requires endgame gear. Drops Judgement Core and Etherwarp Conduit.",
            tips: [
                "Extremely high health and damage — endgame gear required",
                "Has a hit shield — must hit it a certain number of times to break",
                "Summons Voidling minions — ignore or AoE them down",
                "Beacon phase — destroy the beacon or take massive damage",
                "Use Terminator to rapidly break hit shields",
                "Wand of Atonement for healing during the fight",
                "Judgement Core drop (~200M+) is the main prize",
                "Void hits: you must hit the boss in specific windows",
            ],
            recommendedGear: [
                { name: "Terminator Bow", icon: MC_ICON.bow },
                { name: "Warden Helmet", icon: MC_ICON.armor },
                { name: "Necron's Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Inferno Demonlord (T4)",
        icon: MC_ICON.blaze,
        location: "slayer",
        locationName: "Slayer Boss",
        health: "8,000,000",
        damage: "6000",
        xp: "4000",
        difficulty: 85,
        difficultyColor: "var(--red)",
        guide: {
            summary: "Blaze Slayer T4 boss on Crimson Isle. Drops valuable Blaze components.",
            tips: [
                "Must be fought on the Crimson Isle",
                "Has fire aura that damages you when close",
                "Summons fire pillars — move out of them",
                "Quazii phase: hits spawn fire demons",
                "Typhon phase: large AoE attack you must dodge",
                "Use fire resistance and high DPS",
                "Bring Wand of Atonement or high life steal",
                "Drops High Class Archfiend Dice, Duplex enchant",
            ],
            recommendedGear: [
                { name: "Necron's Armor", icon: MC_ICON.armor },
                { name: "Giant's Sword", icon: MC_ICON.sword },
                { name: "Fire Res Potion", icon: MC_ICON.potion },
            ],
        },
    },
    // Dungeons
    {
        name: "Wither Skeleton (Dungeons)",
        icon: MC_ICON.witherSkeleton,
        location: "dungeons",
        locationName: "Catacombs",
        health: "100,000+",
        damage: "1500",
        xp: "500",
        difficulty: 50,
        difficultyColor: "var(--accent)",
        guide: {
            summary: "Common dungeon mobs. Appear throughout all floors of the Catacombs.",
            tips: [
                "Standard dungeon mob — appears on all floors",
                "Higher floors have much tankier versions",
                "Drop Wither Essence for dungeon item upgrades",
                "Use dungeon-specific gear for maximum damage",
                "Clear them quickly for better dungeon score",
                "AoE abilities work great for room clears",
            ],
            recommendedGear: [
                { name: "Livid Dagger", icon: MC_ICON.sword },
                { name: "Adaptive Armor", icon: MC_ICON.armor },
            ],
        },
    },
    {
        name: "Livid (F5 Boss)",
        icon: MC_ICON.witherSkeleton,
        location: "dungeons",
        locationName: "Catacombs F5",
        health: "5,000,000",
        damage: "3000",
        xp: "3000",
        difficulty: 60,
        difficultyColor: "var(--orange)",
        guide: {
            summary: "The Floor 5 boss. Creates copies of himself — find and kill the real one.",
            tips: [
                "Spawns 8 colored copies of himself — only 1 is real",
                "The real Livid changes color periodically",
                "Look for the name tag or use mods to highlight the real one",
                "The fake ones still deal damage — avoid them",
                "When the real one is found, burst it down quickly",
                "Drops Livid Dagger, Shadow Assassin armor pieces",
                "A Berserker or Archer class works best here",
            ],
            recommendedGear: [
                { name: "Shadow Assassin Armor", icon: MC_ICON.armor },
                { name: "Livid Dagger", icon: MC_ICON.sword },
                { name: "Spirit Pet", icon: MC_ICON.goldenApple },
            ],
        },
    },
    {
        name: "Necron (F7 Boss)",
        icon: MC_ICON.wither,
        location: "dungeons",
        locationName: "Catacombs F7",
        health: "50,000,000+",
        damage: "10000",
        xp: "10000",
        difficulty: 90,
        difficultyColor: "var(--red)",
        guide: {
            summary: "The Floor 7 final boss. A multi-phase fight requiring team coordination.",
            tips: [
                "Phase 1 (Maxor): Speed fight — chase the boss down corridors",
                "Phase 2 (Storm): Mage uses Hyperion to kill terminals",
                "Phase 3 (Goldor): Tank terminals — team must step on correct plates",
                "Phase 4 (Necron): The final fight — DPS race with wither shield",
                "Each phase requires different class contributions",
                "Archer carries DPS in the final phase",
                "Drops Necron armor, Wither essence, and rare Handle",
                "Handle drop = 500M+ coins",
            ],
            recommendedGear: [
                { name: "Necron's Armor", icon: MC_ICON.armor },
                { name: "Hyperion", icon: MC_ICON.sword },
                { name: "Terminator", icon: MC_ICON.bow },
            ],
        },
    },
];

// ============================================================
// STRATEGIES DATA
// ============================================================
const STRATEGIES_DATA = [
    {
        title: "Progression Path Tier List",
        subtitle: "The optimal order to progress through SkyBlock",
        icon: "S",
        iconBg: "var(--accent-dim)",
        iconColor: "var(--accent)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Fairy Souls", "Skill Grinding", "Slayer Unlock", "Minion Slots"] },
            { tier: "A", label: "tier-a", items: ["Collections", "Talisman Bag", "Pet Leveling", "Dungeons Unlock"] },
            { tier: "B", label: "tier-b", items: ["Crystal Hollows", "Crimson Isle", "Fishing Skill", "Alchemy Skill"] },
            { tier: "C", label: "tier-c", items: ["Social Skill", "Carpentry", "Runecrafting"] },
        ],
    },
    {
        title: "Best Weapons Tier List",
        subtitle: "Ranked by overall effectiveness and value",
        icon: "W",
        iconBg: "var(--red-dim)",
        iconColor: "var(--red)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Hyperion", "Terminator", "Giant's Sword", "Daedalus Axe"] },
            { tier: "A", label: "tier-a", items: ["Shadow Fury", "Juju Shortbow", "Livid Dagger", "Ice Spray Wand"] },
            { tier: "B", label: "tier-b", items: ["Flower of Truth", "Aspect of the Dragons", "Spirit Sceptre"] },
            { tier: "C", label: "tier-c", items: ["Aspect of the End", "Runaan's Bow", "Raider Axe"] },
        ],
    },
    {
        title: "Best Armor Sets Tier List",
        subtitle: "Ranked for general use across all content",
        icon: "A",
        iconBg: "var(--blue-dim)",
        iconColor: "var(--blue)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Necron's Armor", "Storm Armor", "Goldor Armor", "Warden Helmet"] },
            { tier: "A", label: "tier-a", items: ["Shadow Assassin", "Sorrow Armor", "Terror Armor", "Crimson Armor"] },
            { tier: "B", label: "tier-b", items: ["Strong Dragon", "Wise Dragon", "Frozen Blaze", "Adaptive Armor"] },
            { tier: "C", label: "tier-c", items: ["Ender Armor", "Lapis Armor", "Hardened Diamond"] },
        ],
    },
    {
        title: "Best Pets Tier List",
        subtitle: "Most impactful pets across all activities",
        icon: "P",
        iconBg: "var(--green-dim)",
        iconColor: "var(--green)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Golden Dragon", "Ender Dragon", "Wither Skeleton", "Tiger"] },
            { tier: "A", label: "tier-a", items: ["Elephant", "Bal", "Ammonite", "Baby Yeti"] },
            { tier: "B", label: "tier-b", items: ["Griffin", "Blue Whale", "Spirit", "Parrot"] },
            { tier: "C", label: "tier-c", items: ["Monkey", "Silverfish", "Sheep", "Wolf"] },
        ],
    },
    {
        title: "Dungeon Classes Tier List",
        subtitle: "Best classes for each floor range",
        icon: "D",
        iconBg: "var(--purple-dim)",
        iconColor: "var(--purple)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Archer (F7/M7)", "Mage (F7/M7)", "Berserker (F6-)"] },
            { tier: "A", label: "tier-a", items: ["Tank (F7)", "Healer (M7)", "Berserker (F7)"] },
            { tier: "B", label: "tier-b", items: ["Mage (F5-)", "Healer (F5-)", "Tank (F5-)"] },
            { tier: "C", label: "tier-c", items: ["Archer (Early)", "Healer (Solo)"] },
        ],
    },
    {
        title: "Best Minions for Money",
        subtitle: "Most profitable minion setups ranked",
        icon: "M",
        iconBg: "rgba(249,115,22,0.12)",
        iconColor: "var(--orange)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Snow Minion (T11 + Diamond Spreading)", "Tarantula Minion (T11)", "Revenant Minion (T11)"] },
            { tier: "A", label: "tier-a", items: ["Clay Minion (T11)", "Melon Minion", "Voidling Minion"] },
            { tier: "B", label: "tier-b", items: ["Blaze Minion", "Gold Minion", "Lapis Minion"] },
            { tier: "C", label: "tier-c", items: ["Cobblestone Minion", "Coal Minion", "Wheat Minion"] },
        ],
    },
    {
        title: "Early Game Checklist Strategy",
        subtitle: "Essential steps for new players",
        icon: "E",
        iconBg: "var(--green-dim)",
        iconColor: "var(--green)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Get Lapis Armor ASAP", "Unlock all Fairy Souls", "Get AOTE (Aspect of the End)"] },
            { tier: "A", label: "tier-a", items: ["Max Minion Slots (24+)", "Level All Skills to 15+", "Start Talisman Collection"] },
            { tier: "B", label: "tier-b", items: ["Build First Farm", "Join a Guild", "Complete Romero Quest"] },
            { tier: "C", label: "tier-c", items: ["Unlock Bazaar", "Get Booster Cookie", "Start Slayer Quests"] },
        ],
    },
    {
        title: "Skyblock Money Priorities",
        subtitle: "What to spend your coins on first",
        icon: "$",
        iconBg: "var(--accent-dim)",
        iconColor: "var(--accent)",
        tiers: [
            { tier: "S", label: "tier-s", items: ["Talismans/Accessories", "Weapon Upgrades", "Armor Upgrades"] },
            { tier: "A", label: "tier-a", items: ["Pet Upgrades", "Minion Expansions", "Skill-Boosting Items"] },
            { tier: "B", label: "tier-b", items: ["Farming Tools", "Mining Equipment", "Enchantments"] },
            { tier: "C", label: "tier-c", items: ["Cosmetics", "Island Decorations", "Flex Items"] },
        ],
    },
];
